### PR TITLE
Container image

### PR DESCRIPTION
**Pull request by snh**
Another container image for you @Guenael 😄 

In terms of testing, this runs OK for me, but I wasn't able to pickup any spots, though that is probably due to the poor conditions here at the moment.

### CODE REVIEW

**Comment by Guenael** [comment]
@snh Did you specify the frequency by yourself ??
The default shortcuts for frequencies (ex. 20m) are wrong (wspr and not ft8).
Did you use the direct sampling option? What frequency and other parameters used?

F5LEN was able to decode spots on 2m band.
LMK

**Comment by Guenael** [comment]
BTW I wanted to port your commits from `rtlsdr-wsprd` to this project, but you're faster than me!!
Again, many thanks!

**Comment by snh** [comment]
> The default shortcuts for frequencies (ex. 20m) are wrong (wspr and not ft8).

Ah, I hadn't noticed this. I'll give it another try as I see you just fixed these in https://github.com/Guenael/rtlsdr-ft8d/commit/54deac7eae9bd6abb675aebccc2dff5d3b7ecaf8.

**Comment by Guenael** [comment]
@snh And if you didn't decode anything, use the `-w` option to save the files.
Using a tool like Audacity with the spectrum mode, you can double check if there is a signal, and/or if your are off centered (possible issue with a +/-1500Hz ).
F5LEN successfully decoded a signal on the 2m band, but there are minor things to fix to be "production ready" :)

**Comment by snh** [comment]
@Guenael Can confirm I am successfully decoding now with the correct frequencies. Thanks!

**Comment by Guenael** [comment]
@snh Excellent, thanks for your feedback!!
About the number of spots, keep in mind that the app only reports the CQ calls in the console.

**Pull request merged**
